/*
 * Copyright (C) 2009 Nokia
 * Copyright (C) 2009 Texas Instruments
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#include <linux/module.h>
#include <linux/init.h>

#include "mux.h"


#ifdef CONFIG_OMAP_MUX

#define _OMAP3_MUXENTRY(M0, g, m0, m1, m2, m3, m4, m5, m6, m7)		\
{									\
	.reg_offset	= (OMAP3_CONTROL_PADCONF_##M0##_OFFSET),	\
	.gpio		= (g),						\
	.muxnames	= { m0, m1, m2, m3, m4, m5, m6, m7 },		\
}

#else

#define _OMAP3_MUXENTRY(M0, g, m0, m1, m2, m3, m4, m5, m6, m7)		\
{									\
	.reg_offset	= (OMAP3_CONTROL_PADCONF_##M0##_OFFSET),	\
	.gpio		= (g),						\
}

#endif

#define _OMAP3_BALLENTRY(M0, bb, bt)					\
{									\
	.reg_offset	= (OMAP3_CONTROL_PADCONF_##M0##_OFFSET),	\
	.balls		= { bb, bt },					\
}

/*
 * Superset of all mux modes for omap3
 */
static struct omap_mux __initdata omap3_muxmodes[] = {
	_OMAP3_MUXENTRY(CCDC_DATA0, 99,
		"ccdc_data0", NULL, NULL, "i2c3_sda",
		"gpio_99", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(CCDC_DATA1, 100,
		"ccdc_data1", NULL, NULL, NULL,
		"gpio_100", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(CCDC_DATA2, 101,
		"ccdc_data2", NULL, NULL, NULL,
		"gpio_101", "hw_dbg4", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(CCDC_DATA3, 102,
		"ccdc_data3", NULL, NULL, NULL,
		"gpio_102", "hw_dbg5", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(CCDC_DATA4, 103,
		"ccdc_data4", NULL, NULL, NULL,
		"gpio_103", "hw_dbg6", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(CCDC_DATA5, 104,
		"ccdc_data5", NULL, NULL, NULL,
		"gpio_104", "hw_dbg7", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(CCDC_DATA6, 105,
		"ccdc_data6", NULL, NULL, NULL,
		"gpio_105", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(CCDC_DATA7, 106,
		"ccdc_data7", NULL, NULL, NULL,
		"gpio_106", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MDIO_DATA, 107,
		"mdio_data", "ccdc_data8", NULL, NULL,
		"gpio_107", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MDIO_CLK, 108,
		"mdio_clk", "ccdc_data9", NULL, NULL,
		"gpio_108", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(CCDC_WEN, 98,
		"ccdc_wen", "ccdc_data9", NULL, NULL,
		"gpio_98", "hw_dbg3", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(CCDC_PCLK, 94,
		"ccdc_pclk", NULL, NULL, NULL,
		"gpio_94", "hw_dbg0", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(CCDC_VD, 97,
		"ccdc_vd", NULL, "uart4_cts", NULL,
		"gpio_97", "hw_dbg2", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(CCDC_FIELD, 95,
		"ccdc_field", "ccdc_data8", "uart4_tx", "i2c3_scl",
		"gpio_95", "hw_dbg1", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(RMII_RXER, 167,
		"rmii_rxer", "ccdc_data13", NULL, NULL,
		"gpio_167", "hw_dbg10", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(CCDC_HD, 96,
		"ccdc_hd", NULL, "uart4_rts", NULL,
		"gpio_96", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(RMII_CRS_DV, 111,
		"rmii_crs_dv", "ccdc_data12", NULL, NULL,
		"gpio_111", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(RMII_TXD1, 112,
		"rmii_txd1", "ccdc_data15", NULL, NULL,
		"gpio_112", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(RMII_50MHZ_CLK, 114,
		"rmii_50mhz_clk", NULL, NULL, NULL,
		"gpio_114", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(RMII_TXEN, 113,
		"rmii_txen", NULL, NULL, NULL,
		"gpio_113", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_ACBIAS, 69,
		"dss_acbias", NULL, NULL, NULL,
		"gpio_69", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA0, 70,
		"dss_data0", NULL, "uart1_cts", NULL,
		"gpio_70", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA1, 71,
		"dss_data1", NULL, "uart1_rts", NULL,
		"gpio_71", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA10, 80,
		"dss_data10", NULL, NULL, NULL,
		"gpio_80", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA11, 81,
		"dss_data11", NULL, NULL, NULL,
		"gpio_81", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA12, 82,
		"dss_data12", NULL, NULL, NULL,
		"gpio_82", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA13, 83,
		"dss_data13", NULL, NULL, NULL,
		"gpio_83", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA14, 84,
		"dss_data14", NULL, NULL, NULL,
		"gpio_84", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA15, 85,
		"dss_data15", NULL, NULL, NULL,
		"gpio_85", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA16, 86,
		"dss_data16", NULL, NULL, NULL,
		"gpio_86", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA17, 87,
		"dss_data17", NULL, NULL, NULL,
		"gpio_87", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA18, 88,
		"dss_data18", NULL, "mcspi3_clk", "dss_data0",
		"gpio_88", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA19, 89,
		"dss_data19", NULL, "mcspi3_simo", "dss_data1",
		"gpio_89", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA20, 90,
		"dss_data20", NULL, "mcspi3_somi", "dss_data2",
		"gpio_90", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA21, 91,
		"dss_data21", NULL, "mcspi3_cs0", "dss_data3",
		"gpio_91", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA22, 92,
		"dss_data22", NULL, "mcspi3_cs1", "dss_data4",
		"gpio_92", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA23, 93,
		"dss_data23", NULL, NULL, "dss_data5",
		"gpio_93", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA2, 72,
		"dss_data2", NULL, NULL, NULL,
		"gpio_72", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA3, 73,
		"dss_data3", NULL, NULL, NULL,
		"gpio_73", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA4, 74,
		"dss_data4", NULL, "uart3_rx_irrx", NULL,
		"gpio_74", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA5, 75,
		"dss_data5", NULL, "uart3_tx_irtx", NULL,
		"gpio_75", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA6, 76,
		"dss_data6", NULL, "uart1_tx", NULL,
		"gpio_76", "hw_dbg14", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA7, 77,
		"dss_data7", NULL, "uart1_rx", NULL,
		"gpio_77", "hw_dbg15", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA8, 78,
		"dss_data8", NULL, NULL, NULL,
		"gpio_78", "hw_dbg16", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_DATA9, 79,
		"dss_data9", NULL, NULL, NULL,
		"gpio_79", "hw_dbg17", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_HSYNC, 67,
		"dss_hsync", NULL, NULL, NULL,
		"gpio_67", "hw_dbg13", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_PCLK, 66,
		"dss_pclk", NULL, NULL, NULL,
		"gpio_66", "hw_dbg12", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(DSS_VSYNC, 68,
		"dss_vsync", NULL, NULL, NULL,
		"gpio_68", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(ETK_CLK, 12,
		"etk_clk", "mcbsp5_clkx", "sdmmc3_clk", "hsusb1_stp",
		"gpio_12", "mm1_rxdp", "hsusb1_tll_stp", "hw_dbg0"),
	_OMAP3_MUXENTRY(ETK_CTL, 13,
		"etk_ctl", NULL, "sdmmc3_cmd", "hsusb1_clk",
		"gpio_13", NULL, "hsusb1_tll_clk", "hw_dbg1"),
	_OMAP3_MUXENTRY(ETK_D0, 14,
		"etk_d0", "mcspi3_simo", "sdmmc3_dat4", "hsusb1_data0",
		"gpio_14", "mm1_rxrcv", "hsusb1_tll_data0", "hw_dbg2"),
	_OMAP3_MUXENTRY(ETK_D1, 15,
		"etk_d1", "mcspi3_somi", NULL, "hsusb1_data1",
		"gpio_15", "mm1_txse0", "hsusb1_tll_data1", "hw_dbg3"),
	_OMAP3_MUXENTRY(ETK_D10, 24,
		"etk_d10", NULL, "uart1_rx", "hsusb2_clk",
		"gpio_24", NULL, "hsusb2_tll_clk", "hw_dbg12"),
	_OMAP3_MUXENTRY(ETK_D11, 25,
		"etk_d11", NULL, NULL, "hsusb2_stp",
		"gpio_25", "mm2_rxdp", "hsusb2_tll_stp", "hw_dbg13"),
	_OMAP3_MUXENTRY(ETK_D12, 26,
		"etk_d12", NULL, NULL, "hsusb2_dir",
		"gpio_26", NULL, "hsusb2_tll_dir", "hw_dbg14"),
	_OMAP3_MUXENTRY(ETK_D13, 27,
		"etk_d13", NULL, NULL, "hsusb2_nxt",
		"gpio_27", "mm2_rxdm", "hsusb2_tll_nxt", "hw_dbg15"),
	_OMAP3_MUXENTRY(ETK_D14, 28,
		"etk_d14", NULL, NULL, "hsusb2_data0",
		"gpio_28", "mm2_rxrcv", "hsusb2_tll_data0", "hw_dbg16"),
	_OMAP3_MUXENTRY(ETK_D15, 29,
		"etk_d15", NULL, NULL, "hsusb2_data1",
		"gpio_29", "mm2_txse0", "hsusb2_tll_data1", "hw_dbg17"),
	_OMAP3_MUXENTRY(ETK_D2, 16,
		"etk_d2", "mcspi3_cs0", NULL, "hsusb1_data2",
		"gpio_16", "mm1_txdat", "hsusb1_tll_data2", "hw_dbg4"),
	_OMAP3_MUXENTRY(ETK_D3, 17,
		"etk_d3", "mcspi3_clk", "sdmmc3_dat3", "hsusb1_data7",
		"gpio_17", NULL, "hsusb1_tll_data7", "hw_dbg5"),
	_OMAP3_MUXENTRY(ETK_D4, 18,
		"etk_d4", "mcbsp5_dr", "sdmmc3_dat0", "hsusb1_data4",
		"gpio_18", NULL, "hsusb1_tll_data4", "hw_dbg6"),
	_OMAP3_MUXENTRY(ETK_D5, 19,
		"etk_d5", "mcbsp5_fsx", "sdmmc3_dat1", "hsusb1_data5",
		"gpio_19", NULL, "hsusb1_tll_data5", "hw_dbg7"),
	_OMAP3_MUXENTRY(ETK_D6, 20,
		"etk_d6", "mcbsp5_dx", "sdmmc3_dat2", "hsusb1_data6",
		"gpio_20", NULL, "hsusb1_tll_data6", "hw_dbg8"),
	_OMAP3_MUXENTRY(ETK_D7, 21,
		"etk_d7", "mcspi3_cs1", "sdmmc3_dat7", "hsusb1_data3",
		"gpio_21", "mm1_txen_n", "hsusb1_tll_data3", "hw_dbg9"),
	_OMAP3_MUXENTRY(ETK_D8, 22,
		"etk_d8", "sys_drm_msecure", "sdmmc3_dat6", "hsusb1_dir",
		"gpio_22", NULL, "hsusb1_tll_dir", "hw_dbg10"),
	_OMAP3_MUXENTRY(ETK_D9, 23,
		"etk_d9", "sys_secure_indicator", "sdmmc3_dat5", "hsusb1_nxt",
		"gpio_23", "mm1_rxdm", "hsusb1_tll_nxt", "hw_dbg11"),
	_OMAP3_MUXENTRY(GPMC_A1, 34,
		"gpmc_a1", NULL, NULL, NULL,
		"gpio_34", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_A10, 43,
		"gpmc_a10", "sys_ndmareq3", NULL, NULL,
		"gpio_43", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_A2, 35,
		"gpmc_a2", NULL, NULL, NULL,
		"gpio_35", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_A3, 36,
		"gpmc_a3", NULL, NULL, NULL,
		"gpio_36", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_A4, 37,
		"gpmc_a4", NULL, NULL, NULL,
		"gpio_37", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_A5, 38,
		"gpmc_a5", NULL, NULL, NULL,
		"gpio_38", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_A6, 39,
		"gpmc_a6", NULL, NULL, NULL,
		"gpio_39", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_A7, 40,
		"gpmc_a7", NULL, NULL, NULL,
		"gpio_40", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_A8, 41,
		"gpmc_a8", NULL, NULL, NULL,
		"gpio_41", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_A9, 42,
		"gpmc_a9", "sys_ndmareq2", NULL, NULL,
		"gpio_42", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_CLK, 59,
		"gpmc_clk", NULL, NULL, NULL,
		"gpio_59", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_D10, 46,
		"gpmc_d10", NULL, NULL, NULL,
		"gpio_46", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_D11, 47,
		"gpmc_d11", NULL, NULL, NULL,
		"gpio_47", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_D12, 48,
		"gpmc_d12", NULL, NULL, NULL,
		"gpio_48", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_D13, 49,
		"gpmc_d13", NULL, NULL, NULL,
		"gpio_49", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_D14, 50,
		"gpmc_d14", NULL, NULL, NULL,
		"gpio_50", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_D15, 51,
		"gpmc_d15", NULL, NULL, NULL,
		"gpio_51", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_D8, 44,
		"gpmc_d8", NULL, NULL, NULL,
		"gpio_44", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_D9, 45,
		"gpmc_d9", NULL, NULL, NULL,
		"gpio_45", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_NBE0_CLE, 60,
		"gpmc_nbe0_cle", NULL, NULL, NULL,
		"gpio_60", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_NBE1, 61,
		"gpmc_nbe1", NULL, NULL, NULL,
		"gpio_61", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_NCS1, 52,
		"gpmc_ncs1", NULL, NULL, NULL,
		"gpio_52", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_NCS2, 53,
		"gpmc_ncs2", NULL, NULL, NULL,
		"gpio_53", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_NCS3, 54,
		"gpmc_ncs3", "sys_ndmareq0", NULL, NULL,
		"gpio_54", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_NCS4, 55,
		"gpmc_ncs4", "sys_ndmareq1", "mcbsp4_clkx", "gpt9_pwm_evt",
		"gpio_55", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_NCS5, 56,
		"gpmc_ncs5", "sys_ndmareq2", "mcbsp4_dr", "gpt10_pwm_evt",
		"gpio_56", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_NCS6, 57,
		"gpmc_ncs6", "sys_ndmareq3", "mcbsp4_dx", "gpt11_pwm_evt",
		"gpio_57", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_NCS7, 58,
		"gpmc_ncs7", "gpmc_io_dir", "mcbsp4_fsx", "gpt8_pwm_evt",
		"gpio_58", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_NWP, 62,
		"gpmc_nwp", NULL, NULL, NULL,
		"gpio_62", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_WAIT1, 63,
		"gpmc_wait1", NULL, NULL, NULL,
		"gpio_63", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_WAIT2, 64,
		"gpmc_wait2", NULL, NULL, NULL,
		"gpio_64", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(GPMC_WAIT3, 65,
		"gpmc_wait3", "sys_ndmareq1", NULL, NULL,
		"gpio_65", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(HDQ_SIO, 170,
		"hdq_sio", "sys_altclk", "i2c2_sccbe", "i2c3_sccbe",
		"gpio_170", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(I2C2_SCL, 168,
		"i2c2_scl", NULL, NULL, NULL,
		"gpio_168", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(I2C2_SDA, 183,
		"i2c2_sda", NULL, NULL, NULL,
		"gpio_183", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(I2C3_SCL, 184,
		"i2c3_scl", NULL, NULL, NULL,
		"gpio_184", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(I2C3_SDA, 185,
		"i2c3_sda", NULL, NULL, NULL,
		"gpio_185", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(I2C4_SCL, 0,
		"i2c4_scl", "sys_nvmode1", NULL, NULL,
		NULL, NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(I2C4_SDA, 0,
		"i2c4_sda", "sys_nvmode2", NULL, NULL,
		NULL, NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(JTAG_EMU0, 11,
		"jtag_emu0", NULL, NULL, NULL,
		"gpio_11", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(JTAG_EMU1, 31,
		"jtag_emu1", NULL, NULL, NULL,
		"gpio_31", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCBSP1_CLKR, 156,
		"mcbsp1_clkr", "mcspi4_clk", NULL, NULL,
		"gpio_156", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCBSP1_CLKX, 162,
		"mcbsp1_clkx", NULL, "mcbsp3_clkx", NULL,
		"gpio_162", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCBSP1_DR, 159,
		"mcbsp1_dr", "mcspi4_somi", "mcbsp3_dr", NULL,
		"gpio_159", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCBSP1_DX, 158,
		"mcbsp1_dx", "mcspi4_simo", "mcbsp3_dx", NULL,
		"gpio_158", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCBSP1_FSR, 157,
		"mcbsp1_fsr", NULL, "CCDC_DATAglobal_reset", NULL,
		"gpio_157", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCBSP1_FSX, 161,
		"mcbsp1_fsx", "mcspi4_cs0", "mcbsp3_fsx", NULL,
		"gpio_161", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCBSP2_CLKX, 117,
		"mcbsp2_clkx", NULL, NULL, NULL,
		"gpio_117", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCBSP2_DR, 118,
		"mcbsp2_dr", NULL, NULL, NULL,
		"gpio_118", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCBSP2_DX, 119,
		"mcbsp2_dx", NULL, NULL, NULL,
		"gpio_119", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCBSP2_FSX, 116,
		"mcbsp2_fsx", NULL, NULL, NULL,
		"gpio_116", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCBSP3_CLKX, 142,
		"mcbsp3_clkx", "uart2_tx", NULL, NULL,
		"gpio_142", "hsusb3_tll_data6", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCBSP3_DR, 141,
		"mcbsp3_dr", "uart2_rts", NULL, NULL,
		"gpio_141", "hsusb3_tll_data5", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCBSP3_DX, 140,
		"mcbsp3_dx", "uart2_cts", NULL, NULL,
		"gpio_140", "hsusb3_tll_data4", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCBSP3_FSX, 143,
		"mcbsp3_fsx", "uart2_rx", NULL, NULL,
		"gpio_143", "hsusb3_tll_data7", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCBSP4_CLKX, 152,
		"mcbsp4_clkx", NULL, NULL, NULL,
		"gpio_152", "hsusb3_tll_data1", "mm3_txse0", "safe_mode"),
	_OMAP3_MUXENTRY(MCBSP4_DR, 153,
		"mcbsp4_dr", NULL, NULL, NULL,
		"gpio_153", "hsusb3_tll_data0", "mm3_rxrcv", "safe_mode"),
	_OMAP3_MUXENTRY(MCBSP4_DX, 154,
		"mcbsp4_dx", NULL, NULL, NULL,
		"gpio_154", "hsusb3_tll_data2", "mm3_txdat", "safe_mode"),
	_OMAP3_MUXENTRY(MCBSP4_FSX, 155,
		"mcbsp4_fsx", NULL, NULL, NULL,
		"gpio_155", "hsusb3_tll_data3", "mm3_txen_n", "safe_mode"),
	_OMAP3_MUXENTRY(MCBSP_CLKS, 160,
		"mcbsp_clks", NULL, "CCDC_DATAshutter", NULL,
		"gpio_160", "uart1_cts", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCSPI1_CLK, 171,
		"mcspi1_clk", "sdmmc2_dat4", NULL, NULL,
		"gpio_171", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCSPI1_CS0, 174,
		"mcspi1_cs0", "sdmmc2_dat7", NULL, NULL,
		"gpio_174", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCSPI1_CS1, 175,
		"mcspi1_cs1", NULL, NULL, "sdmmc3_cmd",
		"gpio_175", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCSPI1_CS2, 176,
		"mcspi1_cs2", NULL, NULL, "sdmmc3_clk",
		"gpio_176", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCSPI1_CS3, 177,
		"mcspi1_cs3", NULL, "hsusb2_tll_data2", "hsusb2_data2",
		"gpio_177", "mm2_txdat", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCSPI1_SIMO, 172,
		"mcspi1_simo", "sdmmc2_dat5", NULL, NULL,
		"gpio_172", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCSPI1_SOMI, 173,
		"mcspi1_somi", "sdmmc2_dat6", NULL, NULL,
		"gpio_173", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCSPI2_CLK, 178,
		"mcspi2_clk", NULL, "hsusb2_tll_data7", "hsusb2_data7",
		"gpio_178", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCSPI2_CS0, 181,
		"mcspi2_cs0", "gpt11_pwm_evt",
		"hsusb2_tll_data6", "hsusb2_data6",
		"gpio_181", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCSPI2_CS1, 182,
		"mcspi2_cs1", "gpt8_pwm_evt",
		"hsusb2_tll_data3", "hsusb2_data3",
		"gpio_182", "mm2_txen_n", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCSPI2_SIMO, 179,
		"mcspi2_simo", "gpt9_pwm_evt",
		"hsusb2_tll_data4", "hsusb2_data4",
		"gpio_179", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(MCSPI2_SOMI, 180,
		"mcspi2_somi", "gpt10_pwm_evt",
		"hsusb2_tll_data5", "hsusb2_data5",
		"gpio_180", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SDMMC1_CLK, 120,
		"sdmmc1_clk", NULL, NULL, NULL,
		"gpio_120", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SDMMC1_CMD, 121,
		"sdmmc1_cmd", NULL, NULL, NULL,
		"gpio_121", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SDMMC1_DAT0, 122,
		"sdmmc1_dat0", NULL, NULL, NULL,
		"gpio_122", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SDMMC1_DAT1, 123,
		"sdmmc1_dat1", NULL, NULL, NULL,
		"gpio_123", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SDMMC1_DAT2, 124,
		"sdmmc1_dat2", NULL, NULL, NULL,
		"gpio_124", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SDMMC1_DAT3, 125,
		"sdmmc1_dat3", NULL, NULL, NULL,
		"gpio_125", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SDMMC1_DAT4, 126,
		"sdmmc1_dat4", NULL, NULL, NULL,
		"gpio_126", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SDMMC1_DAT5, 127,
		"sdmmc1_dat5", NULL, NULL, NULL,
		"gpio_127", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SDMMC1_DAT6, 128,
		"sdmmc1_dat6", NULL, NULL, NULL,
		"gpio_128", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SDMMC1_DAT7, 129,
		"sdmmc1_dat7", NULL, NULL, NULL,
		"gpio_129", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SDMMC2_CLK, 130,
		"sdmmc2_clk", "mcspi3_clk", NULL, NULL,
		"gpio_130", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SDMMC2_CMD, 131,
		"sdmmc2_cmd", "mcspi3_simo", NULL, NULL,
		"gpio_131", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SDMMC2_DAT0, 132,
		"sdmmc2_dat0", "mcspi3_somi", NULL, NULL,
		"gpio_132", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SDMMC2_DAT1, 133,
		"sdmmc2_dat1", NULL, NULL, NULL,
		"gpio_133", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SDMMC2_DAT2, 134,
		"sdmmc2_dat2", "mcspi3_cs1", NULL, NULL,
		"gpio_134", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SDMMC2_DAT3, 135,
		"sdmmc2_dat3", "mcspi3_cs0", NULL, NULL,
		"gpio_135", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SDMMC2_DAT4, 136,
		"sdmmc2_dat4", "sdmmc2_dir_dat0", NULL, "sdmmc3_dat0",
		"gpio_136", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SDMMC2_DAT5, 137,
		"sdmmc2_dat5", "sdmmc2_dir_dat1",
		"CCDC_DATAglobal_reset", "sdmmc3_dat1",
		"gpio_137", "hsusb3_tll_stp", "mm3_rxdp", "safe_mode"),
	_OMAP3_MUXENTRY(SDMMC2_DAT6, 138,
		"sdmmc2_dat6", "sdmmc2_dir_cmd", "CCDC_DATAshutter", "sdmmc3_dat2",
		"gpio_138", "hsusb3_tll_dir", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SDMMC2_DAT7, 139,
		"sdmmc2_dat7", "sdmmc2_clkin", NULL, "sdmmc3_dat3",
		"gpio_139", "hsusb3_tll_nxt", "mm3_rxdm", "safe_mode"),
	_OMAP3_MUXENTRY(SDRC_CKE0, 0,
		"sdrc_cke0", NULL, NULL, NULL,
		NULL, NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SDRC_CKE1, 0,
		"sdrc_cke1", NULL, NULL, NULL,
		NULL, NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SYS_BOOT0, 2,
		"sys_boot0", NULL, NULL, NULL,
		"gpio_2", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SYS_BOOT1, 3,
		"sys_boot1", NULL, NULL, NULL,
		"gpio_3", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SYS_BOOT2, 4,
		"sys_boot2", NULL, NULL, NULL,
		"gpio_4", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SYS_BOOT3, 5,
		"sys_boot3", NULL, NULL, NULL,
		"gpio_5", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SYS_BOOT4, 6,
		"sys_boot4", "sdmmc2_dir_dat2", NULL, NULL,
		"gpio_6", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SYS_BOOT5, 7,
		"sys_boot5", "sdmmc2_dir_dat3", NULL, NULL,
		"gpio_7", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SYS_BOOT6, 8,
		"sys_boot6", NULL, NULL, NULL,
		"gpio_8", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SYS_CLKOUT1, 10,
		"sys_clkout1", NULL, NULL, NULL,
		"gpio_10", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SYS_CLKOUT2, 186,
		"sys_clkout2", NULL, NULL, NULL,
		"gpio_186", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SYS_CLKREQ, 1,
		"sys_clkreq", NULL, NULL, NULL,
		"gpio_1", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SYS_NIRQ, 0,
		"sys_nirq", NULL, NULL, NULL,
		"gpio_0", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SYS_NRESWARM, 30,
		"sys_nreswarm", NULL, NULL, NULL,
		"gpio_30", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(SYS_OFF_MODE, 9,
		"sys_off_mode", NULL, NULL, NULL,
		"gpio_9", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(UART1_CTS, 150,
		"uart1_cts", NULL, NULL, NULL,
		"gpio_150", "hsusb3_tll_clk", NULL, "safe_mode"),
	_OMAP3_MUXENTRY(UART1_RTS, 149,
		"uart1_rts", NULL, NULL, NULL,
		"gpio_149", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(UART1_RX, 151,
		"uart1_rx", NULL, "mcbsp1_clkr", "mcspi4_clk",
		"gpio_151", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(UART1_TX, 148,
		"uart1_tx", NULL, NULL, NULL,
		"gpio_148", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(UART2_CTS, 144,
		"uart2_cts", "mcbsp3_dx", "gpt9_pwm_evt", NULL,
		"gpio_144", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(UART2_RTS, 145,
		"uart2_rts", "mcbsp3_dr", "gpt10_pwm_evt", NULL,
		"gpio_145", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(UART2_RX, 147,
		"uart2_rx", "mcbsp3_fsx", "gpt8_pwm_evt", NULL,
		"gpio_147", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(UART2_TX, 146,
		"uart2_tx", "mcbsp3_clkx", "gpt11_pwm_evt", NULL,
		"gpio_146", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(UART3_CTS_RCTX, 163,
		"uart3_cts_rctx", NULL, NULL, NULL,
		"gpio_163", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(UART3_RTS_SD, 164,
		"uart3_rts_sd", NULL, NULL, NULL,
		"gpio_164", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(UART3_RX_IRRX, 165,
		"uart3_rx_irrx", NULL, NULL, NULL,
		"gpio_165", NULL, NULL, "safe_mode"),
	_OMAP3_MUXENTRY(UART3_TX_IRTX, 166,
		"uart3_tx_irtx", NULL, NULL, NULL,
		"gpio_166", NULL, NULL, "safe_mode"),
	{ .reg_offset = OMAP_MUX_TERMINATOR },
};


/*
 * Balls for CUS package
 * 423-pin s-PBGA Package, 0.65mm Ball Pitch (Bottom)
 */
#if defined(CONFIG_OMAP_MUX) && defined(CONFIG_DEBUG_FS)		\
		&& defined(CONFIG_OMAP_PACKAGE_CUS)
static struct omap_ball __initdata omap3_cus_ball[] = {
	_OMAP3_BALLENTRY(CCDC_DATA0, "ab18", NULL),
	_OMAP3_BALLENTRY(CCDC_DATA1, "ac18", NULL),
	_OMAP3_BALLENTRY(CCDC_DATA2, "g19", NULL),
	_OMAP3_BALLENTRY(CCDC_DATA3, "f19", NULL),
	_OMAP3_BALLENTRY(CCDC_DATA4, "g20", NULL),
	_OMAP3_BALLENTRY(CCDC_DATA5, "b21", NULL),
	_OMAP3_BALLENTRY(CCDC_DATA6, "l24", NULL),
	_OMAP3_BALLENTRY(CCDC_DATA7, "k24", NULL),
	_OMAP3_BALLENTRY(DSS_ACBIAS, "j21", NULL),
	_OMAP3_BALLENTRY(DSS_DATA0, "ac19", NULL),
	_OMAP3_BALLENTRY(DSS_DATA1, "ab19", NULL),
	_OMAP3_BALLENTRY(DSS_DATA10, "ac22", NULL),
	_OMAP3_BALLENTRY(DSS_DATA11, "ac23", NULL),
	_OMAP3_BALLENTRY(DSS_DATA12, "ab22", NULL),
	_OMAP3_BALLENTRY(DSS_DATA13, "y22", NULL),
	_OMAP3_BALLENTRY(DSS_DATA14, "w22", NULL),
	_OMAP3_BALLENTRY(DSS_DATA15, "v22", NULL),
	_OMAP3_BALLENTRY(DSS_DATA16, "j22", NULL),
	_OMAP3_BALLENTRY(DSS_DATA17, "g23", NULL),
	_OMAP3_BALLENTRY(DSS_DATA18, "g24", NULL),
	_OMAP3_BALLENTRY(DSS_DATA19, "h23", NULL),
	_OMAP3_BALLENTRY(DSS_DATA2, "ad20", NULL),
	_OMAP3_BALLENTRY(DSS_DATA20, "d23", NULL),
	_OMAP3_BALLENTRY(DSS_DATA21, "k22", NULL),
	_OMAP3_BALLENTRY(DSS_DATA22, "v21", NULL),
	_OMAP3_BALLENTRY(DSS_DATA23, "w21", NULL),
	_OMAP3_BALLENTRY(DSS_DATA3, "ac20", NULL),
	_OMAP3_BALLENTRY(DSS_DATA4, "ad21", NULL),
	_OMAP3_BALLENTRY(DSS_DATA5, "ac21", NULL),
	_OMAP3_BALLENTRY(DSS_DATA6, "d24", NULL),
	_OMAP3_BALLENTRY(DSS_DATA7, "e23", NULL),
	_OMAP3_BALLENTRY(DSS_DATA8, "e24", NULL),
	_OMAP3_BALLENTRY(DSS_DATA9, "f23", NULL),
	_OMAP3_BALLENTRY(DSS_HSYNC, "e22", NULL),
	_OMAP3_BALLENTRY(DSS_PCLK, "g22", NULL),
	_OMAP3_BALLENTRY(DSS_VSYNC, "f22", NULL),
	_OMAP3_BALLENTRY(ETK_CLK, "ac1", NULL),
	_OMAP3_BALLENTRY(ETK_CTL, "ad3", NULL),
	_OMAP3_BALLENTRY(ETK_D0, "ad6", NULL),
	_OMAP3_BALLENTRY(ETK_D1, "ac6", NULL),
	_OMAP3_BALLENTRY(ETK_D10, "ac3", NULL),
	_OMAP3_BALLENTRY(ETK_D11, "ac9", NULL),
	_OMAP3_BALLENTRY(ETK_D12, "ac10", NULL),
	_OMAP3_BALLENTRY(ETK_D13, "ad11", NULL),
	_OMAP3_BALLENTRY(ETK_D14, "ac11", NULL),
	_OMAP3_BALLENTRY(ETK_D15, "ad12", NULL),
	_OMAP3_BALLENTRY(ETK_D2, "ac7", NULL),
	_OMAP3_BALLENTRY(ETK_D3, "ad8", NULL),
	_OMAP3_BALLENTRY(ETK_D4, "ac5", NULL),
	_OMAP3_BALLENTRY(ETK_D5, "ad2", NULL),
	_OMAP3_BALLENTRY(ETK_D6, "ac8", NULL),
	_OMAP3_BALLENTRY(ETK_D7, "ad9", NULL),
	_OMAP3_BALLENTRY(ETK_D8, "ac4", NULL),
	_OMAP3_BALLENTRY(ETK_D9, "ad5", NULL),
	_OMAP3_BALLENTRY(GPMC_A1, "k4", NULL),
	_OMAP3_BALLENTRY(GPMC_A10, "g2", NULL),
	_OMAP3_BALLENTRY(GPMC_A2, "k3", NULL),
	_OMAP3_BALLENTRY(GPMC_A3, "k2", NULL),
	_OMAP3_BALLENTRY(GPMC_A4, "j4", NULL),
	_OMAP3_BALLENTRY(GPMC_A5, "j3", NULL),
	_OMAP3_BALLENTRY(GPMC_A6, "j2", NULL),
	_OMAP3_BALLENTRY(GPMC_A7, "j1", NULL),
	_OMAP3_BALLENTRY(GPMC_A8, "h1", NULL),
	_OMAP3_BALLENTRY(GPMC_A9, "h2", NULL),
	_OMAP3_BALLENTRY(GPMC_CLK, "w2", NULL),
	_OMAP3_BALLENTRY(GPMC_D10, "u1", NULL),
	_OMAP3_BALLENTRY(GPMC_D11, "r3", NULL),
	_OMAP3_BALLENTRY(GPMC_D12, "t3", NULL),
	_OMAP3_BALLENTRY(GPMC_D13, "u2", NULL),
	_OMAP3_BALLENTRY(GPMC_D14, "v1", NULL),
	_OMAP3_BALLENTRY(GPMC_D15, "v2", NULL),
	_OMAP3_BALLENTRY(GPMC_D8, "r2", NULL),
	_OMAP3_BALLENTRY(GPMC_D9, "t2", NULL),
	_OMAP3_BALLENTRY(GPMC_NBE0_CLE, "k5", NULL),
	_OMAP3_BALLENTRY(GPMC_NBE1, "l1", NULL),
	_OMAP3_BALLENTRY(GPMC_NCS3, "d2", NULL),
	_OMAP3_BALLENTRY(GPMC_NCS4, "f4", NULL),
	_OMAP3_BALLENTRY(GPMC_NCS5, "g5", NULL),
	_OMAP3_BALLENTRY(GPMC_NCS6, "f3", NULL),
	_OMAP3_BALLENTRY(GPMC_NCS7, "g4", NULL),
	_OMAP3_BALLENTRY(GPMC_NWP, "e1", NULL),
	_OMAP3_BALLENTRY(GPMC_WAIT3, "c2", NULL),
	_OMAP3_BALLENTRY(HDQ_SIO, "a24", NULL),
	_OMAP3_BALLENTRY(I2C2_SCL, "ac15", NULL),
	_OMAP3_BALLENTRY(I2C2_SDA, "ac14", NULL),
	_OMAP3_BALLENTRY(I2C3_SCL, "ac13", NULL),
	_OMAP3_BALLENTRY(I2C3_SDA, "ac12", NULL),
	_OMAP3_BALLENTRY(I2C4_SCL, "y16", NULL),
	_OMAP3_BALLENTRY(I2C4_SDA, "y15", NULL),
	_OMAP3_BALLENTRY(JTAG_EMU0, "ac24", NULL),
	_OMAP3_BALLENTRY(JTAG_EMU1, "ad24", NULL),
	_OMAP3_BALLENTRY(MCBSP1_CLKR, "w19", NULL),
	_OMAP3_BALLENTRY(MCBSP1_CLKX, "v18", NULL),
	_OMAP3_BALLENTRY(MCBSP1_DR, "y18", NULL),
	_OMAP3_BALLENTRY(MCBSP1_DX, "w18", NULL),
	_OMAP3_BALLENTRY(MCBSP1_FSR, "ab20", NULL),
	_OMAP3_BALLENTRY(MCBSP1_FSX, "aa19", NULL),
	_OMAP3_BALLENTRY(MCBSP2_CLKX, "t21", NULL),
	_OMAP3_BALLENTRY(MCBSP2_DR, "v19", NULL),
	_OMAP3_BALLENTRY(MCBSP2_DX, "r20", NULL),
	_OMAP3_BALLENTRY(MCBSP2_FSX, "v20", NULL),
	_OMAP3_BALLENTRY(MCBSP3_CLKX, "w4", NULL),
	_OMAP3_BALLENTRY(MCBSP3_DR, "v5", NULL),
	_OMAP3_BALLENTRY(MCBSP3_DX, "v6", NULL),
	_OMAP3_BALLENTRY(MCBSP3_FSX, "v4", NULL),
	_OMAP3_BALLENTRY(MCBSP_CLKS, "aa18", NULL),
	_OMAP3_BALLENTRY(MCSPI1_CLK, "t5", NULL),
	_OMAP3_BALLENTRY(MCSPI1_CS0, "t6", NULL),
	_OMAP3_BALLENTRY(MCSPI1_CS3, "r5", NULL),
	_OMAP3_BALLENTRY(MCSPI1_SIMO, "r4", NULL),
	_OMAP3_BALLENTRY(MCSPI1_SOMI, "t4", NULL),
	_OMAP3_BALLENTRY(MCSPI2_CLK, "n5", NULL),
	_OMAP3_BALLENTRY(MCSPI2_CS0, "m5", NULL),
	_OMAP3_BALLENTRY(MCSPI2_CS1, "m4", NULL),
	_OMAP3_BALLENTRY(MCSPI2_SIMO, "n4", NULL),
	_OMAP3_BALLENTRY(MCSPI2_SOMI, "n3", NULL),
	_OMAP3_BALLENTRY(SDMMC1_CLK, "m23", NULL),
	_OMAP3_BALLENTRY(SDMMC1_CMD, "l23", NULL),
	_OMAP3_BALLENTRY(SDMMC1_DAT0, "m22", NULL),
	_OMAP3_BALLENTRY(SDMMC1_DAT1, "m21", NULL),
	_OMAP3_BALLENTRY(SDMMC1_DAT2, "m20", NULL),
	_OMAP3_BALLENTRY(SDMMC1_DAT3, "n23", NULL),
	_OMAP3_BALLENTRY(SDMMC1_DAT4, "n22", NULL),
	_OMAP3_BALLENTRY(SDMMC1_DAT5, "n21", NULL),
	_OMAP3_BALLENTRY(SDMMC1_DAT6, "n20", NULL),
	_OMAP3_BALLENTRY(SDMMC1_DAT7, "p24", NULL),
	_OMAP3_BALLENTRY(SDMMC2_CLK, "y1", NULL),
	_OMAP3_BALLENTRY(SDMMC2_CMD, "ab5", NULL),
	_OMAP3_BALLENTRY(SDMMC2_DAT0, "ab3", NULL),
	_OMAP3_BALLENTRY(SDMMC2_DAT1, "y3", NULL),
	_OMAP3_BALLENTRY(SDMMC2_DAT2, "w3", NULL),
	_OMAP3_BALLENTRY(SDMMC2_DAT3, "v3", NULL),
	_OMAP3_BALLENTRY(SDMMC2_DAT4, "ab2", NULL),
	_OMAP3_BALLENTRY(SDMMC2_DAT5, "aa2", NULL),
	_OMAP3_BALLENTRY(SDMMC2_DAT6, "y2", NULL),
	_OMAP3_BALLENTRY(SDMMC2_DAT7, "aa1", NULL),
	_OMAP3_BALLENTRY(SYS_BOOT0, "ab12", NULL),
	_OMAP3_BALLENTRY(SYS_BOOT1, "ac16", NULL),
	_OMAP3_BALLENTRY(SYS_BOOT2, "ad17", NULL),
	_OMAP3_BALLENTRY(SYS_BOOT3, "ad18", NULL),
	_OMAP3_BALLENTRY(SYS_BOOT4, "ac17", NULL),
	_OMAP3_BALLENTRY(SYS_BOOT5, "ab16", NULL),
	_OMAP3_BALLENTRY(SYS_BOOT6, "aa15", NULL),
	_OMAP3_BALLENTRY(SYS_CLKOUT1, "y7", NULL),
	_OMAP3_BALLENTRY(SYS_CLKOUT2, "aa6", NULL),
	_OMAP3_BALLENTRY(SYS_CLKREQ, "y13", NULL),
	_OMAP3_BALLENTRY(SYS_NIRQ, "w16", NULL),
	_OMAP3_BALLENTRY(SYS_NRESWARM, "y10", NULL),
	_OMAP3_BALLENTRY(SYS_OFF_MODE, "ad23", NULL),
	_OMAP3_BALLENTRY(UART1_CTS, "ac2", NULL),
	_OMAP3_BALLENTRY(UART1_RTS, "w6", NULL),
	_OMAP3_BALLENTRY(UART1_RX, "v7", NULL),
	_OMAP3_BALLENTRY(UART1_TX, "w7", NULL),
	_OMAP3_BALLENTRY(UART3_CTS_RCTX, "a23", NULL),
	_OMAP3_BALLENTRY(UART3_RTS_SD, "b23", NULL),
	_OMAP3_BALLENTRY(UART3_RX_IRRX, "b24", NULL),
	_OMAP3_BALLENTRY(UART3_TX_IRTX, "c23", NULL),
	{ .reg_offset = OMAP_MUX_TERMINATOR },
};
#else
#define omap3_cus_ball	 NULL
#endif




int __init omap3_mux_init(struct omap_board_mux *board_subset, int flags)
{
	struct omap_mux *package_subset;
	struct omap_ball *package_balls;

	switch (flags & OMAP_PACKAGE_MASK) {
	case OMAP_PACKAGE_CUS:
		package_subset = NULL;
		package_balls = omap3_cus_ball;
		break;

	default:
		pr_err("%s Unknown omap package, mux disabled\n", __func__);
		return -EINVAL;
	}

	return omap_mux_init("core", 0,
			     OMAP3_CONTROL_PADCONF_MUX_PBASE,
			     OMAP3_CONTROL_PADCONF_MUX_SIZE,
			     omap3_muxmodes, package_subset, board_subset,
			     package_balls);
}
